---
- name: Initialize the GPUs
  command: /bin/bash /usr/local/bin/cuda_init.sh

- name: ZZ CUDA Restart server
  command: sleep 2 && /sbin/shutdown -r now "Node software upgrade reboot"
  async: 1
  poll: 0
  ignore_errors: true
  when: cuda_packages_installation.changed and cuda_restart_node_on_install == True

# define the variable running_as_ansible_pull in the ansible-pull playbook, like local.yml 
- name: ZZ CUDA Wait for server to restart
  local_action: wait_for host="{{ ansible_ssh_host | default(inventory_hostname) }}" 
                state=started 
                delay=30 
                timeout=300
  become: false
  when: cuda_restart_node_on_install == True and (running_as_ansible_pull is not defined or running_as_ansible_pull == False)
